/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with a username and password
         * @description Exchanges username+password credentials for a session access token (a signed JWT presented as a Bearer token on subsequent owner-surface requests). Unauthenticated; the tenant is resolved from the Host header. Available only when the password login method is enabled on the instance.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in as the instance superadmin
         * @description Exchanges the superadmin username+password for a session token on the instance-level admin surface. Unauthenticated; not tenant-scoped. Returns 404 when no superadmin is configured (the admin surface is disabled).
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current superadmin */
        get: operations["adminGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a tenant (superadmin) */
        post: operations["adminCreateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an owner with a password credential in a tenant (superadmin) */
        post: operations["adminCreateOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current owner/tenant */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the owner's lists */
        get: operations["listLists"];
        put?: never;
        /** Create a list */
        post: operations["createList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        /** Get a list (owner view) */
        get: operations["getList"];
        put?: never;
        post?: never;
        /** Delete a list */
        delete: operations["deleteList"];
        options?: never;
        head?: never;
        /** Update a list */
        patch: operations["updateList"];
        trace?: never;
    };
    "/api/v1/lists/{listId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        /** List items in a list */
        get: operations["listItems"];
        put?: never;
        /** Add an item */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an item */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /** Update an item */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/item-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch item metadata from a product URL (browser auto-add)
         * @description Server-side scrape of a product page (OpenGraph / Twitter cards / JSON-LD) returning a draft item the client can review before creating. Never creates an item itself; the client POSTs the confirmed draft to /items.
         */
        post: operations["previewItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the tenant's custom domains */
        get: operations["listDomains"];
        put?: never;
        /**
         * Add a custom domain (bring-your-own-domain)
         * @description Registers a custom hostname for the tenant and returns the CNAME target to point it at. TLS is provisioned on-demand once the CNAME verifies (deferred feature; see ADR-0001).
         */
        post: operations["addDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a custom domain */
        delete: operations["deleteDomain"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check the domain's DNS TXT verification record
         * @description Looks up the DNS TXT record at _yaadegar-verify.<hostname> and marks the domain verified if it contains the verification_token. Idempotent: an already-verified domain returns verified; a missing or non-matching record returns the domain still unverified (retry after publishing the record) — not an error. Only verified domains route requests to the tenant.
         */
        post: operations["verifyDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{shareSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
            };
            cookie?: never;
        };
        /**
         * View a shared list (anonymous)
         * @description Public read view of a list by its share_slug. Shows items and each item's availability (available / reserved / being co-bought) but never who reserved or is buying. Disabled lists (past event_date, or inactive) return 410.
         */
        get: operations["getPublicList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{shareSlug}/items/{itemId}/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve an item (anonymous giver)
         * @description Claims an item so nobody duplicates the gift. Optional name/email are used only server-side (e.g. decay reminders) and are never shown to others.
         *     On a full_guest list the reservation is active immediately and a one-time capability token is returned (201). On an email_confirmed list the reservation is held provisionally as pending_confirmation and a confirmation link is emailed; the response is 202 with status pending_confirmation and no token — the giver must confirm (see /public/reservations/confirm) before the reservation activates and the token is issued. An email_confirmed reserve requires giver_email.
         */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/reservations/{reservationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Release a reservation (anonymous giver)
         * @description Requires the capability token returned at creation.
         */
        delete: operations["releaseReservation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/reservations/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email_confirmed reservation via its emailed token (anonymous)
         * @description Activates the pending_confirmation reservation identified by the one-time token emailed to the giver at reserve time, and returns the capability token to release it later. Idempotent: re-confirming an already-active reservation returns 200 with status active and no new capability token (it cannot be re-issued). The token stops working once the confirm window elapses and the reservation auto-expires.
         */
        post: operations["confirmReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/decay-release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a stale reservation via its one-click decay token (anonymous)
         * @description Releases the reservation identified by a one-click decay-release token, emailed to the reserver when their reservation goes stale. Single-use: the token stops working once the reservation is released or auto-expires.
         */
        post: operations["releaseByDecayToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/decay-keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew a stale reservation via its one-click decay token (anonymous)
         * @description Renews (keeps) the reservation identified by a one-click decay-keep token, emailed to the reserver alongside the release link. Resets the decay clock and invalidates both one-click tokens. Single-use: the token stops working once used or once the reservation auto-expires.
         */
        post: operations["keepByDecayToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{shareSlug}/items/{itemId}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pledge a share toward co-buying an item
         * @description Opt-in group gifting. The giver pledges a share of the price and provides a contact that is revealed ONLY if a two-sided match forms and both parties confirm. Returns a capability token to poll/confirm/withdraw later.
         */
        post: operations["createContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/contributions/{contributionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: string;
            };
            cookie?: never;
        };
        /**
         * Get a contribution and any pending match (anonymous giver)
         * @description Lets a contributor discover a match proposed after their pledge — the server also emails them a link out-of-band, but this endpoint is the pollable path so EITHER party (including the first pledger) can find the match_id to confirm. Requires the capability token.
         */
        get: operations["getContribution"];
        put?: never;
        post?: never;
        /**
         * Withdraw a contribution (anonymous giver)
         * @description Withdraw a pledge before a match is confirmed. Requires the capability token. Once a match is both_confirmed, withdrawal is no longer allowed (409).
         */
        delete: operations["withdrawContribution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        /**
         * Read a co-buying match's state (anonymous giver)
         * @description Returns a match's proposed/confirmed state so a contributor can load the confirm/decline handshake — including cross-device from the emailed link. Authorized by X-Capability-Token carrying EITHER the contributor's capability token (same-browser) or the scoped match-action token (cross-device); the token must belong to this match. Contacts are revealed only once the match is both_confirmed (ADR-0002 §6).
         */
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/matches/{matchId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm or decline a proposed co-buying match
         * @description Each matched contributor confirms via their capability token. Contacts are revealed to each other only after BOTH confirm; a decline dissolves the match.
         */
        post: operations["confirmMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem detail. */
        Problem: {
            /** @default about:blank */
            type: string;
            title?: string;
            status?: number;
            detail?: string;
        };
        /** @description An exact monetary amount as minor units plus ISO-4217 currency. */
        Money: {
            /** @description Amount in minor units (e.g. cents). */
            amount_minor: number;
            /** @example EUR */
            currency: string;
        };
        User: {
            id?: string;
            name?: string;
            tenant?: {
                id?: string;
                /** @example alice */
                subdomain?: string;
            };
        };
        AdminIdentity: {
            id?: string;
            username?: string;
        };
        Tenant: {
            id?: string;
            subdomain?: string;
        };
        AdminTenantCreate: {
            /** @description Lowercase slug; the tenant is addressed at <subdomain>.<base-domain>. */
            subdomain: string;
        };
        AdminOwner: {
            id?: string;
            tenant_id?: string;
            email?: string;
        };
        AdminOwnerCreate: {
            tenant_id: string;
            email: string;
            /** @description Plaintext; hashed server-side (argon2id). The email doubles as the login username. */
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description Signed JWT to present as `Authorization: Bearer <token>`. */
            access_token: string;
            /**
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
            /** @description Access-token lifetime in seconds. */
            expires_in: number;
        };
        NullableBool: boolean | null;
        NullableInt: number | null;
        NullableString: string | null;
        /** Format: date */
        NullableDate: string | null;
        /** @enum {string} */
        ListVisibility: "public" | "unlisted" | "private";
        ListCreate: {
            title: string;
            visibility?: components["schemas"]["ListVisibility"];
            /**
             * Format: date
             * @description Optional. After this date the list auto-disables (read-only).
             */
            event_date?: string | null;
            /** @description Reservation-decay period override. Omit (or null) to inherit the instance default; 0 means off (this list never decays); N means a reservation may sit N days before the reserver is asked to keep or release it. */
            decay_days?: number | null;
            /** @description Reserver-identity tier override (ADR-0007): full_guest | email_confirmed | registered. Omit (or null) to inherit the instance default. full_guest reserves with a one-time capability token; email_confirmed requires the giver to confirm an email before the reservation activates; registered (deferred) requires a giver account. */
            reserver_tier?: string | null;
            /** @description email_confirmed confirm-window override in minutes (ADR-0007). Omit (or null) to inherit the instance default; 0 means an unconfirmed hold never auto-expires; N means it expires N minutes after reserve if unconfirmed. */
            reserver_confirm_window?: number | null;
        };
        ListUpdate: {
            title?: string;
            visibility?: components["schemas"]["ListVisibility"];
            event_date?: components["schemas"]["NullableDate"];
            decay_days?: components["schemas"]["NullableInt"];
            active?: boolean;
            reserver_tier?: components["schemas"]["NullableString"];
            reserver_confirm_window?: components["schemas"]["NullableInt"];
            /** @description List-level default for whether items may be co-bought (#100). Items inherit this unless they set their own override. Defaults to true; a new list is always created co-buy-enabled and is toggled here. */
            allow_cobuy?: boolean;
        };
        List: {
            id?: string;
            title?: string;
            visibility?: components["schemas"]["ListVisibility"];
            share_slug?: string;
            /** Format: date */
            event_date?: string | null;
            /** @description The decay-period override; null means inheriting the instance default. */
            decay_days?: number | null;
            /** @description The reserver-identity tier override; null inherits the instance default. */
            reserver_tier?: string | null;
            /** @description The confirm-window override in minutes; null inherits the instance default. */
            reserver_confirm_window?: number | null;
            /** @description The list-level default for whether items may be co-bought (#100). */
            allow_cobuy?: boolean;
            active?: boolean;
            item_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        ListPage: {
            items?: components["schemas"]["List"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        /**
         * @description Availability only. Never reveals who reserved or is buying.
         * @enum {string}
         */
        ItemAvailability: "available" | "reserved" | "co_buying" | "purchased";
        /** @description Scraped/proposed item fields (any may be null). */
        ItemDraft: {
            name?: string | null;
            /** Format: uri */
            url?: string | null;
            /** Format: uri */
            image_url?: string | null;
            price?: components["schemas"]["Money"];
        };
        ItemCreate: {
            name: string;
            /** Format: uri */
            url?: string | null;
            /** Format: uri */
            image_url?: string | null;
            price?: components["schemas"]["Money"];
            note?: string | null;
            /** @default 0 */
            priority: number;
            /** @default 1 */
            quantity_wanted: number;
            /** @description Per-item co-buy override (#100): omit (or null) to inherit the list default, true/false to force co-buying on/off for this item. */
            allow_cobuy?: boolean | null;
        };
        ItemUpdate: {
            name?: string;
            /** Format: uri */
            url?: string | null;
            /** Format: uri */
            image_url?: string | null;
            price?: components["schemas"]["Money"];
            note?: string | null;
            priority?: number;
            quantity_wanted?: number;
            allow_cobuy?: components["schemas"]["NullableBool"];
        };
        Item: {
            id?: string;
            list_id?: string;
            name?: string;
            /** Format: uri */
            url?: string | null;
            /** Format: uri */
            image_url?: string | null;
            price?: components["schemas"]["Money"];
            note?: string | null;
            priority?: number;
            quantity_wanted?: number;
            availability?: components["schemas"]["ItemAvailability"];
            /** @description How many units are reserved (owner view). This is a count only and never identifies who reserved them (ADR-0002 §5). */
            reserved_quantity?: number;
            /** @description The per-item co-buy override (#100), owner view: null means inheriting the list default, true/false an explicit override. */
            allow_cobuy?: boolean | null;
        };
        ItemPage: {
            items?: components["schemas"]["Item"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        /** @description An item as a giver sees it — availability only, no reserver identity. */
        PublicItem: {
            id?: string;
            name?: string;
            /** Format: uri */
            url?: string | null;
            /** Format: uri */
            image_url?: string | null;
            price?: components["schemas"]["Money"];
            note?: string | null;
            availability?: components["schemas"]["ItemAvailability"];
            amount_funded?: components["schemas"]["Money"];
            /** @description Whether this item may be co-bought (#100, resolved from the item override and list default). The giver UI shows the chip-in affordance only when this is true AND the item is priced. */
            allow_cobuy?: boolean;
        };
        PublicList: {
            title?: string;
            /** Format: date */
            event_date?: string | null;
            items?: components["schemas"]["PublicItem"][];
        };
        ReservationCreate: {
            giver_name?: string | null;
            /** Format: email */
            giver_email?: string | null;
            /** @default 1 */
            quantity: number;
        };
        ReservationCreated: {
            reservation_id: string;
            /**
             * @description active — the reservation holds the item now (full_guest tier). pending_confirmation — an email_confirmed reservation holding the item provisionally until the giver confirms via the emailed link; no capability token is issued until then.
             * @enum {string}
             */
            status: "active" | "pending_confirmation";
            /** @description The release handle, returned once. Present only for an active reservation; absent while pending_confirmation (issued at confirm). */
            capability_token?: string;
        };
        ReservationConfirmed: {
            reservation_id: string;
            /**
             * @description Always active on a 200 — the reservation now holds the item, whether this request activated it or it was already confirmed.
             * @enum {string}
             */
            status: "active";
            /** @description Returned once, on the confirming request that activates the reservation. Absent on an idempotent re-confirm of an already-active reservation (it cannot be re-issued). */
            capability_token?: string;
        };
        /**
         * @description tracks a pledge through the co-buying handshake. The terminal statuses (declined, withdrawn, expired) free the item; expired is set by the match auto-expiry sweep when a proposed match's confirm window elapses.
         * @enum {string}
         */
        ContributionStatus: "pending" | "matched" | "confirmed" | "declined" | "withdrawn" | "expired";
        ContributionCreate: {
            /** @description The share this giver pledges toward the item's price. */
            pledged: components["schemas"]["Money"];
            giver_name?: string | null;
            /**
             * Format: email
             * @description Revealed to a co-buyer only after a mutually-confirmed match.
             */
            contact_email: string;
        };
        /** @description A giver's pledge toward co-buying an item (giver-facing view). */
        Contribution: {
            id?: string;
            item_id?: string;
            pledged?: components["schemas"]["Money"];
            status?: components["schemas"]["ContributionStatus"];
            /** @description Set when a match involving this contribution is pending; POST it to confirm. */
            match_id?: string | null;
        };
        ContributionCreated: {
            contribution_id?: string;
            /** @description Returned once. */
            capability_token?: string;
            /** @description A proposed match if this pledge completed funding; else null. */
            match?: components["schemas"]["Match"] | null;
        };
        /**
         * @description is the lifecycle state of a co-buying match. The terminal `expired` is set by the match auto-expiry sweep when a proposed match sits past its confirm window; its pledges are released.
         * @enum {string}
         */
        MatchState: "proposed" | "both_confirmed" | "done" | "declined" | "expired";
        /** @description A co-buying handshake between contributions on one item. */
        Match: {
            id?: string;
            item_id?: string;
            state?: components["schemas"]["MatchState"];
            contribution_ids?: string[];
            /** @description Populated only once state is both_confirmed. */
            contacts?: string[];
        };
        Domain: {
            id?: string;
            hostname?: string;
            /** @description Point your CNAME here. */
            cname_target?: string;
            verified?: boolean;
            /** @enum {string} */
            tls_status?: "none" | "pending" | "active";
            /** @description Publish this as a DNS TXT record at _yaadegar-verify.<hostname>, then call verify. A proof-of-control challenge, not a secret. */
            verification_token?: string;
        };
    };
    responses: {
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but not permitted to act on this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request body failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist (or is not visible to the caller). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many failed attempts; the caller is temporarily rate-limited. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ListId: string;
        ItemId: string;
        /** @description A list's opaque, unguessable share slug. */
        ShareSlug: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication succeeded; a session access token is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Password login is not enabled on this instance. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication succeeded; a superadmin session token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The admin surface is not enabled on this instance. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated superadmin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIdentity"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The admin surface is not enabled on this instance. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminCreateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTenantCreate"];
            };
        };
        responses: {
            /** @description The created tenant. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminCreateOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminOwnerCreate"];
            };
        };
        responses: {
            /** @description The created owner (never includes the password hash). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOwner"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user and their tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLists: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the owner's lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListCreate"];
            };
        };
        responses: {
            /** @description The created list. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list, owner view (includes reservation availability). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListUpdate"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listItems: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: components["parameters"]["ListId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description The created item. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description The updated item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    previewItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description Best-effort scraped draft. Fields may be null if not found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDraft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The URL could not be fetched or parsed; fall back to manual entry. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's domains and their verification/TLS status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addDomain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example gifts.example.com */
                    hostname: string;
                };
            };
        };
        responses: {
            /** @description The registered (unverified) domain, including the verification_token to publish as a DNS TXT record at _yaadegar-verify.<hostname>. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    verifyDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The domain with its (possibly now-updated) verified state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The public list view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicList"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The list is no longer active (past its event date or disabled). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Reservation active; capability token returned once (full_guest). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationCreated"];
                };
            };
            /** @description Reservation held pending email confirmation (email_confirmed); a confirmation link was emailed. No token until confirmed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description The item is already fully reserved. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The list is no longer active (past its event date or disabled). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description An email_confirmed reservation could not send its confirmation email; the provisional hold was rolled back and the slot freed. Transient — retry the reservation. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    releaseReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Released. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    confirmReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Reservation active. Capability token present on first confirm. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationConfirmed"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The confirm window elapsed; the reservation expired and the link is spent. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    releaseByDecayToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Released. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The reservation already expired; the link is no longer valid. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    keepByDecayToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Renewed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description The reservation already expired; the link is no longer valid. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A list's opaque, unguessable share slug. */
                shareSlug: components["parameters"]["ShareSlug"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionCreate"];
            };
        };
        responses: {
            /** @description Contribution recorded; token returned once. May include a proposed match. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Co-buying is turned off for this item by the owner (#100). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The item is already fully funded or reserved. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The list is no longer active (past its event date or disabled). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contribution, including match_id when a match is pending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    withdrawContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contributionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The match state; contacts present only when both_confirmed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The scoped match-action token has expired. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    confirmMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "confirm" | "decline";
                };
            };
        };
        responses: {
            /** @description The updated match state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The match is already resolved (both-confirmed or declined). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
